---
- hosts: remoteservers
 # strategy: free
  become: true
  become_method: sudo
  tasks:
    #- name: "Create Empty file"
    #  file:
    #    path: "/root/ansible.txt"
    #    state: touch
    #  become: yes
    - name: Create a User.
      user:
        name: newuser
        state: present
        password:
   # - name: Let's copy our executable script to remote location, execute script and get result back.
      #remote_user: root
      #sudo: yes
      #hosts: crunchify-group
     # tasks:
    - name: Transfer executable script script
      copy: src=/root/K8-cluster-setup-datafeedai/ansible.sh dest=/root mode=0777
    - name: Execute the script
      command: sh /root/ansible.sh > logs.txt 2>&1 &

